apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: micro-webapi-config-server
  labels:
    group: web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appapiconfigserver
      tier: backend
  template:
    metadata:
      labels:
        app: appapiconfigserver
        tier: backend
    spec:
      containers:
        - image: 12482/micro-webapi_configserver:1
          name: appapiconfigserver
          resources: {hub.docker.com}
status: {}