apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: micro-webapi-server
  labels:
    group: web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      tier: backend
  template:
    metadata:
      labels:
        app: api-gateway
        tier: backend
    spec:
      containers:
        - image: 12482/micro-webapi_apigateway:1
          name: api-gateway
          resources: {hub.docker.com}
status: {}