apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: appapiconfigserver
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 8012
      targetPort: 8012
  type: LoadBalancer