apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: api-gateway
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 8082
      targetPort: 8082
  type: LoadBalancer