apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discoveryservice
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 8010
      targetPort: 8010
  type: LoadBalancer